# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_gcp_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_gcp_project'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

target-path: "target"  # directory where dbt will write compiled files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_gcp_project: # Le nom du projet doit correspondre ici
    # Staging models will be created as views in the silver dataset
    staging:
      +materialized: view
      +schema: 'silver_{{ var("env") }}' 
      
    # Intermediate models will be created as views in the silver dataset
    int:
      +materialized: view
      +schema: 'silver_{{ var("env") }}'
      
    # Marts models will be created as tables in the gold dataset
    marts:
      +materialized: table
      +schema: 'gold_{{ var("env") }}'

# This section is for variables that you want to use in your dbt project.
vars:
  env: 'dev'