dbt_gcp_project:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      bronze_dataset: "bronze_dev"
      silver_dataset: "silver_dev"
      gold_dataset: "gold_dev"
      threads: 2
      location: "us-central1"

    staging:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      bronze_dataset: "bronze_staging"
      silver_dataset: "silver_staging"
      gold_dataset: "gold_staging"
      threads: 2
      location: "us-central1"

    prod:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      bronze_dataset: "bronze_prod"
      silver_dataset: "silver_prod"
      gold_dataset: "gold_prod"
      threads: 4
      location: "us-central1"