dbt_gcp_project:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      dataset: "bronze_dev"
      threads: 2
      location: "us-central1"

    staging:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      dataset: "bronze_staging"
      threads: 2
      location: "us-central1"

    prod:
      type: bigquery
      method: oauth
      project: "dbt-project-dvd-rent-464116"
      dataset: "bronze_prod"
      threads: 4
      location: "us-central1"
